### ISSUE TITLE
Unable to run this project, always getting errors while installing the requirements

### ISSUE THREAD

**Issue by frankmrunltd** [anuj-glitch/Disease-Prediction-using-Django-and-machine-learning#27]
Please can anyone who have used this project before help me out how I can successfully run this project. I have tried following the steps and instructions but I keep getting errors. I will be very grateful for your help.. below is the errors I keep getting

`PS C:\Users\frank1\Downloads\2023 Sch Projects\Disease Prediction\third one\Disease-Prediction-using-Django-and-machine-learning-master\My environs> pip install -r requirements.txt
Collecting django==3.0.3 (from -r requirements.txt (line 2))
  Using cached Django-3.0.3-py3-none-any.whl (7.5 MB)
Collecting joblib==0.14.1 (from -r requirements.txt (line 3))
  Using cached joblib-0.14.1-py2.py3-none-any.whl (294 kB)
Collecting scikit-learn==0.21.3 (from -r requirements.txt (line 4))
  Using cached scikit-learn-0.21.3.tar.gz (12.2 MB)
  Preparing metadata (setup.py) ... done
Collecting psycopg2==2.8.4 (from -r requirements.txt (line 5))
  Using cached psycopg2-2.8.4.tar.gz (377 kB)
  Preparing metadata (setup.py) ... done
Collecting pytz (from django==3.0.3->-r requirements.txt (line 2))
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
Collecting sqlparse>=0.2.2 (from django==3.0.3->-r requirements.txt (line 2))
  Using cached sqlparse-0.4.4-py3-none-any.whl (41 kB)
Collecting asgiref~=3.2 (from django==3.0.3->-r requirements.txt (line 2))
  Using cached asgiref-3.7.2-py3-none-any.whl (24 kB)
Requirement already satisfied: numpy>=1.11.0 in c:\users\frank1\anaconda3\envs\predictionprojectshps\lib\site-packages (from scikit-learn==0.21.3->-r requirements.txt (line 4)) (1.25.0)
Requirement already satisfied: scipy>=0.17.0 in c:\users\frank1\anaconda3\envs\predictionprojectshps\lib\site-packages (from scikit-learn==0.21.3->-r requirements.txt (line 4)) (1.11.1)
Building wheels for collected packages: scikit-learn, psycopg2
  Building wheel for scikit-learn (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      Partial import of sklearn during the build process.
      C:\Users\frank1\AppData\Local\Temp\pip-install-ja58v9pl\scikit-learn_01a97c41f93f40139a8bf256c7bc75f2\setup.py:122: DeprecationWarning:
     
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
     
     
        from numpy.distutils.command.build_ext import build_ext  # noqa
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\frank1\AppData\Local\Temp\pip-install-ja58v9pl\scikit-learn_01a97c41f93f40139a8bf256c7bc75f2\setup.py", line 290, in <module>
          setup_package()
        File "C:\Users\frank1\AppData\Local\Temp\pip-install-ja58v9pl\scikit-learn_01a97c41f93f40139a8bf256c7bc75f2\setup.py", line 286, in setup_package
          setup(**metadata)
        File "C:\Users\frank1\anaconda3\envs\predictionprojectSHPS\Lib\site-packages\numpy\distutils\core.py", line 135, in setup
          config = configuration()
                   ^^^^^^^^^^^^^^^
        File "C:\Users\frank1\AppData\Local\Temp\pip-install-ja58v9pl\scikit-learn_01a97c41f93f40139a8bf256c7bc75f2\setup.py", line 174, in configuration
          config.add_subpackage('sklearn')
        File "C:\Users\frank1\anaconda3\envs\predictionprojectSHPS\Lib\site-packages\numpy\distutils\misc_util.py", line 1050, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\frank1\anaconda3\envs\predictionprojectSHPS\Lib\site-packages\numpy\distutils\misc_util.py", line 1016, in get_subpackage
          config = self._get_configuration_from_setup_py(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\frank1\anaconda3\envs\predictionprojectSHPS\Lib\site-packages\numpy\distutils\misc_util.py", line 958, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\frank1\AppData\Local\Temp\pip-install-ja58v9pl\scikit-learn_01a97c41f93f40139a8bf256c7bc75f2\sklearn\setup.py", line 62, in configuration
          config.add_subpackage('utils')
        File "C:\Users\frank1\anaconda3\envs\predictionprojectSHPS\Lib\site-packages\numpy\distutils\misc_util.py", line 1050, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\frank1\anaconda3\envs\predictionprojectSHPS\Lib\site-packages\numpy\distutils\misc_util.py", line 1016, in get_subpackage
          config = self._get_configuration_from_setup_py(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\frank1\anaconda3\envs\predictionprojectSHPS\Lib\site-packages\numpy\distutils\misc_util.py", line 958, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\frank1\AppData\Local\Temp\pip-install-ja58v9pl\scikit-learn_01a97c41f93f40139a8bf256c7bc75f2\sklearn\utils\setup.py", line 8, in configuration
          from Cython import Tempita
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-learn
  Running setup.py clean for scikit-learn
  Building wheel for psycopg2 (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      C:\Users\frank1\anaconda3\envs\predictionprojectSHPS\Lib\site-packages\setuptools\config\setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
     
              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.
     
              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
     
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
     
      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\psycopg2
      copying lib\compat.py -> build\lib.win-amd64-cpython-311\psycopg2
      copying lib\errorcodes.py -> build\lib.win-amd64-cpython-311\psycopg2
      copying lib\errors.py -> build\lib.win-amd64-cpython-311\psycopg2
      copying lib\extensions.py -> build\lib.win-amd64-cpython-311\psycopg2
      copying lib\extras.py -> build\lib.win-amd64-cpython-311\psycopg2
      copying lib\pool.py -> build\lib.win-amd64-cpython-311\psycopg2
      copying lib\sql.py -> build\lib.win-amd64-cpython-311\psycopg2
      copying lib\tz.py -> build\lib.win-amd64-cpython-311\psycopg2
      copying lib\_ipaddress.py -> build\lib.win-amd64-cpython-311\psycopg2
      copying lib\_json.py -> build\lib.win-amd64-cpython-311\psycopg2
      copying lib\_lru_cache.py -> build\lib.win-amd64-cpython-311\psycopg2
      copying lib\_range.py -> build\lib.win-amd64-cpython-311\psycopg2
      copying lib\__init__.py -> build\lib.win-amd64-cpython-311\psycopg2
      running build_ext
      building 'psycopg2._psycopg' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psycopg2
  Running setup.py clean for psycopg2
Failed to build scikit-learn psycopg2
ERROR: Could not build wheels for scikit-learn, psycopg2, which is required to install pyproject.toml-based projects`

**Comment by Matthew-cel** [comment]
when i run python manage.py makemigrations it shows this error : ModuleNotFoundError: No module named 'cgi'
please what do i do

**Comment by aravinthsamys** [comment]
try python 3.7.9
 version
