### ISSUE TITLE
Database connection

### ISSUE THREAD

**Issue by kalissus** [anuj-glitch/Disease-Prediction-using-Django-and-machine-learning#3]
is there any need to be changed to get connected to the database or it gets connected automatically?

**Comment by anuj-glitch** [comment]
Who are you?

**Comment by anuj-glitch** [comment]
Yes, first you have to manually create a DB instance on PostgreSQL named "predico",
use PgAdmin for that.

**Comment by tirthjivani** [comment]
I have added this to the readme. I also faced the same issue.

**Comment by T2061** [comment]
I tried to run your code but it didn't predicted any

**Comment by tirthjivani** [comment]
@T2061 it runs perfectly fine 👍🏻

**Comment by sevenhills87** [comment]
Help Me! What is the Admin User Name And Password

**Comment by anuj-glitch** [comment]
You can create a new admin username using Django's - create superuser commands

**Comment by sevenhills87** [comment]
Thank you sir . I used this project for my post graduation

**Comment by ridham-sood** [comment]
can u plzz help me out
@anuj-glitch

**Comment by sauharda4** [comment]
how to create a new environment and run the commands?

**Comment by Manojkumar0308** [comment]
System check identified 5 issues (0 silenced).
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 230, in ensure_connection
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 25, in inner
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 211, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 25, in inner
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 199, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?

**Comment by sarathkd** [comment]
sir please explain the code of disease prediction
